USE master;
CREATE DATABASE LogbookDB

USE LogbookDB;
CREATE TABLE Users(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(MAX) NOT NULL,
	Login NVARCHAR(MAX) NOT NULL,
	Password NVARCHAR(MAX) NOT NULL,
	UserType INT DEFAULT 0 NOT NULL,
	Date_Reg DATE NOT NULL
)
CREATE TABLE PrintedTypes(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(MAX) NOT NULL
)
INSERT INTO PrintedTypes(Name) VALUES
	('Книга'),
	('Журнал'),
	('Газета')


CREATE TABLE PrintedProducts(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TypeID INT NOT NULL FOREIGN KEY(TypeID) REFERENCES PrintedTypes(ID),
	Name NVARCHAR(MAX) NOT NULL,
	Author NVARCHAR(MAX) NOT NULL,
	IsAvaible BIT NOT NULL DEFAULT 1,
	Cover NVARCHAR(MAX)
)
CREATE TABLE Records(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	UserID INT NOT NULL FOREIGN KEY(UserID) REFERENCES Users(ID),
	ProductID INT NOT NULL FOREIGN KEY(ProductID) REFERENCES PrintedProducts(ID),
	IsReturned BIT NOT NULL DEFAULT 0,
	Date_Issue DATE NOT NULL,
	Date_Return DATE NOT NULL
)

CREATE TABLE Visits(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	UserID INT FOREIGN KEY(UserID) REFERENCES Users(ID),
	Date_Visit DATE NOT NULL
)