//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintedProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintedProduct()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public bool IsAvaible { get; set; }
        public string Cover { get; set; }
    
        public virtual PrintedType PrintedType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
    }
}
