//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public bool IsReturned { get; set; }
        public System.DateTime Date_Issue { get; set; }
        public System.DateTime Date_Return { get; set; }
    
        public virtual PrintedProduct PrintedProduct { get; set; }
        public virtual User User { get; set; }
    }
}
